# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://gimhaniu.github.io/
baseurl: /home/
title: Gimhani Uthpala
author: Gimhani Uthpala
description: I love programming !
avatar: profile.jpg
email: gimhanieuthpala@email.com
github: GimhaniU # username
twitter: gimhaniu
linkedin: gimhaniuthpala
stackoverflow: users/4848659/gimhani
#Comment out if you don't want disqus 
#disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]

theme: jekyll-theme-cayman
